// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/wu-xie-888/micro-wire/client/handle"
)

// Injectors from wire.go:

func initApp() (*handle.Options, error) {
	engine, err := handle.NewWeb()
	if err != nil {
		return nil, err
	}
	service, err := handle.NewService()
	if err != nil {
		return nil, err
	}
	options, err := handle.NewOptions(engine, service)
	if err != nil {
		return nil, err
	}
	return options, nil
}
